# Generated by Django 3.2.6 on 2022-03-22 22:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('login', models.CharField(max_length=15, verbose_name='Логин')),
                ('email', models.CharField(max_length=40, verbose_name='Почта')),
                ('password', models.CharField(max_length=30, verbose_name='Пароль')),
                ('name', models.CharField(max_length=30, verbose_name='Имя')),
                ('description', models.CharField(max_length=300, verbose_name='Описание')),
                ('chat_ids', models.CharField(max_length=300)),
                ('profile_photo', models.ImageField(blank=True, upload_to='photos/profile_photos', verbose_name='Фото аккаунта')),
            ],
        ),
    ]
