# Generated by Django 4.0.4 on 2022-04-27 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profile', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='followed',
            field=models.TextField(blank=True, verbose_name='followed'),
        ),
        migrations.AlterField(
            model_name='user',
            name='followers',
            field=models.TextField(blank=True, verbose_name='followers'),
        ),
    ]
