# Generated by Django 4.0.4 on 2022-04-28 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profile', '0002_alter_user_followed_alter_user_followers'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='followed',
        ),
        migrations.AddField(
            model_name='user',
            name='follows',
            field=models.TextField(blank=True, verbose_name='follows'),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(max_length=40, verbose_name='Почта'),
        ),
    ]
