# Generated by Django 4.0.4 on 2022-04-29 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profile', '0003_remove_user_followed_user_follows_alter_user_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='flags_found',
            field=models.TextField(blank=True, verbose_name='flags_found'),
        ),
    ]
