# Generated by Django 4.0.4 on 2022-04-29 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profile', '0004_user_flags_found'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='used_theme',
            field=models.IntegerField(default='-1', verbose_name='used_theme'),
        ),
    ]
