# Generated by Django 4.0.4 on 2022-05-04 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profile', '0006_alter_user_used_theme'),
    ]

    operations = [
        migrations.CreateModel(
            name='Publication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.IntegerField(verbose_name='Автор')),
                ('text', models.TextField(verbose_name='Текст')),
                ('image', models.ImageField(blank=True, upload_to='photos/publication_images', verbose_name='Фото')),
                ('like_ids', models.TextField(verbose_name='ID лайков')),
                ('comment_ids', models.TextField(verbose_name='ID сообщений')),
                ('time_created', models.CharField(max_length=10, verbose_name='Время создания')),
            ],
            options={
                'verbose_name': 'Пост',
                'verbose_name_plural': 'Посты',
            },
        ),
        migrations.AlterModelOptions(
            name='chat',
            options={'verbose_name': 'Чат', 'verbose_name_plural': 'Чаты'},
        ),
        migrations.AlterModelOptions(
            name='message',
            options={'verbose_name': 'Сообщение', 'verbose_name_plural': 'Сообщения'},
        ),
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name': 'Пользователь', 'verbose_name_plural': 'Пользователи'},
        ),
        migrations.AlterField(
            model_name='chat',
            name='image',
            field=models.ImageField(blank=True, upload_to='photos/chat_images', verbose_name='Фото'),
        ),
        migrations.AlterField(
            model_name='chat',
            name='message_ids',
            field=models.TextField(verbose_name='ID сообщений'),
        ),
        migrations.AlterField(
            model_name='chat',
            name='name',
            field=models.CharField(max_length=40, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='chat',
            name='users',
            field=models.CharField(max_length=150, verbose_name='Участники'),
        ),
        migrations.AlterField(
            model_name='message',
            name='autor',
            field=models.IntegerField(verbose_name='Автор'),
        ),
        migrations.AlterField(
            model_name='message',
            name='is_read',
            field=models.BooleanField(verbose_name='Прочитано'),
        ),
        migrations.AlterField(
            model_name='message',
            name='read_by',
            field=models.CharField(max_length=150, verbose_name='Кем прочитано'),
        ),
        migrations.AlterField(
            model_name='message',
            name='text',
            field=models.CharField(max_length=1000, verbose_name='Сообщение'),
        ),
        migrations.AlterField(
            model_name='message',
            name='time_sent',
            field=models.CharField(max_length=10, verbose_name='Время отправки'),
        ),
    ]
