# Generated by Django 4.0.4 on 2022-05-18 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profile', '0007_publication_alter_chat_options_alter_message_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_email_set_to_be_seen_or_not_by_user',
            field=models.BooleanField(default=0, verbose_name='is_email_set_to_be_seen_or_not_by_user'),
        ),
        migrations.AlterField(
            model_name='chat',
            name='name',
            field=models.CharField(max_length=32, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='chat',
            name='users',
            field=models.CharField(max_length=512, verbose_name='Участники'),
        ),
        migrations.AlterField(
            model_name='message',
            name='read_by',
            field=models.CharField(max_length=512, verbose_name='Кем прочитано'),
        ),
        migrations.AlterField(
            model_name='message',
            name='text',
            field=models.CharField(max_length=1024, verbose_name='Сообщение'),
        ),
        migrations.AlterField(
            model_name='message',
            name='time_sent',
            field=models.CharField(max_length=13, verbose_name='Время отправки'),
        ),
        migrations.AlterField(
            model_name='publication',
            name='comment_ids',
            field=models.TextField(blank=True, verbose_name='ID сообщений'),
        ),
        migrations.AlterField(
            model_name='publication',
            name='like_ids',
            field=models.TextField(blank=True, verbose_name='ID лайков'),
        ),
        migrations.AlterField(
            model_name='publication',
            name='time_created',
            field=models.CharField(max_length=13, verbose_name='Время создания'),
        ),
        migrations.AlterField(
            model_name='user',
            name='chat_ids',
            field=models.CharField(blank=True, max_length=512),
        ),
        migrations.AlterField(
            model_name='user',
            name='description',
            field=models.CharField(blank=True, max_length=128, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(max_length=64, verbose_name='Почта'),
        ),
        migrations.AlterField(
            model_name='user',
            name='login',
            field=models.CharField(max_length=36, verbose_name='Логин'),
        ),
        migrations.AlterField(
            model_name='user',
            name='name',
            field=models.CharField(max_length=64, verbose_name='Имя'),
        ),
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(max_length=64, verbose_name='Пароль'),
        ),
    ]
