# Generated by Django 4.0.4 on 2022-06-10 04:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profile', '0008_user_is_email_set_to_be_seen_or_not_by_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publication',
            name='image',
            field=models.FileField(blank=True, upload_to='photos/publication_images', verbose_name='Фото'),
        ),
    ]
